export enum SummerizationModules {
	FALSE = "FALSE",
	CATEGORY = "CATEGORY",
	CATEGORY_MAINFIELD = "CATEGORY_MAINFIELD",
	CUSTOMER = "CUSTOMER",
	MACHINE = "MACHINE",
	USER = "USER",
	USER_GROUP = "USER_GROUP",
	USER_ROLE = "USER_ROLE",
}

export enum SummerizationTimes {
	FALSE = "FALSE",
	DAY = "DAY",
	INTERVAL = "INTERVAL",
	MONTH = "MONTH",
	QUARTER = "QUARTER",
	WEEK = "WEEK",
	YEAR = "YEAR",
}

export enum JobPermissionLevel {
	NONE = "NONE",
	SELF = "SELF",
	GROUP = "GROUP",
	ALL = "ALL",
}

export enum FieldUIElement {
	TEXT = "TEXT",
	TEXTAREA = "TEXTAREA",
	BOOLEAN = "BOOLEAN",
	RADIO = "RADIO",
	RANGE = "RANGE",
	COLOR = "COLOR",
	MAP = "MAP",
	NUMBER = "NUMBER",
	NUMBER_INTERVAL = "NUMBER_INTERVAL",
	TIME = "TIME",
	TIME_INTERVAL = "TIME_INTERVAL",

	SELECT = "SELECT",
	SELECT_TIME = "SELECT_TIME",
	SELECT_NUMBER = "SELECT_NUMBER",
	SELECT_TIME_INTERVAL = "SELECT_TIME_INTERVAL",

	MACHINE = "MACHINE",
	MACHINE_TIME = "MACHINE_TIME",
	MACHINE_NUMBER = "MACHINE_NUMBER",
	MACHINE_TIME_INTERVAL = "MACHINE_TIME_INTERVAL",
	COMBINED_TIME = "COMBINED_TIME",
	COMBINED_NUMBER = "COMBINED_NUMBER",
}
